name: isar_example
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #for generating unqiue ids
  uuid: ^4.5.1
  
  #for navigation
  go_router: ^14.3.0

  #packages related to riverpod(state mgmt)
  flutter_riverpod: ^2.5.3
  riverpod_annotation: ^2.3.5

  #packages related to isar db
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  #for retrieving path of common directories
  path_provider: ^2.1.4

  #for network requests
  dio: ^5.7.0

  #for simple key-value persistant local storage
  shared_preferences: ^2.3.2
  
  #for localization and internationalization
  intl: ^0.19.0


#dev_dependencies are used for packages that are only used in development
dev_dependencies:
  flutter_test:
    sdk: flutter

  #default linting rules
  flutter_lints: ^3.0.0
  
  #for custom linting rules
  custom_lint: ^0.5.11
  #custom linting rules for riverpod
  riverpod_lint: ^2.1.1
  
  #for generating dart code files
  build_runner: ^2.4.11
  #for generating isar db files
  isar_generator: ^3.1.0+1
  #for generating riverpod files
  riverpod_generator: ^2.3.3

flutter:

  uses-material-design: true

  generate: true